name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: pnpm install
    - name: Run ESLint
      run: pnpm run lint
    - name: Type-check
      run: pnpm run type-check
    - name: Build project
      run: pnpm run build